---
version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker image build -t theasp/novnc:latest -f Dockerfile .
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
              docker image ls
              docker push theasp/novnc:latest
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build
  weekly:
    triggers:
      - schedule:
          cron: "0 12 * * 2"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
