pipeline {
    agent any


    stages {
         stage('Checkout') {
            steps {
                // Checkout only the 'backend' directory
                git url: 'https://github.com/zk2k2/edubox.git', 
                    branch: 'main', 
                    sparseCheckoutPaths: [['backend']]
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose -p edubox-backend up -d --build'
        }
    }
}
}
